### ISSUE TITLE
Add instructions on how to launch directly from Docker

### ISSUE THREAD

**Issue by cmichi** [paritytech/substrate-contracts-node#41]
Should be in the form of https://github.com/paritytech/cargo-contract#installation-using-docker-image.

The Docker which is referred there already contains the executable of the latest `substrate-contracts-node` release ([this is done here](https://github.com/paritytech/scripts/blob/master/dockerfiles/contracts-ci-linux/Dockerfile#L53-L56)), so we can just use this CI image here as well. I think the only that needs to be modified is to remove the folder sharing arguments and add some port forwarding ones.

## ToDo

- [ ] Add the instructions to the readme in this repo. 
- [ ] Add pointer to `ink-docs` where we describe how to launch `subtrate-contracts-node`.
- [ ] Add pointer to `substrate-docs` where we describe how to launch `subtrate-contracts-node`
